### ISSUE TITLE
package.json refers to non existent git repository

### ISSUE THREAD

**Issue by delcypher** [rhiokim/haroopad#417]
I tried building haroopad but didn't get very far.

```
npm install
npm ERR! git clone git://github.com/excellenteasy/grunt-shell.git Cloning into bare repository '/home/dan/.npm/_git-remotes/git-github-com-excellenteasy-grunt-shell-git-9d3bcae4'...
npm ERR! git clone git://github.com/excellenteasy/grunt-shell.git warning: templates not found /home/dan/.npm/_git_remotes/_templates
npm ERR! git clone git://github.com/excellenteasy/grunt-shell.git fatal: remote error: 
npm ERR! git clone git://github.com/excellenteasy/grunt-shell.git   Repository not found.
npm ERR! Linux 3.16.3-1-ARCH
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! node v0.10.32
npm ERR! npm  v2.1.2
npm ERR! code 128

npm ERR! Command failed: Cloning into bare repository '/home/dan/.npm/_git-remotes/git-github-com-excellenteasy-grunt-shell-git-9d3bcae4'...
npm ERR! warning: templates not found /home/dan/.npm/_git_remotes/_templates
npm ERR! fatal: remote error: 
npm ERR!   Repository not found.
npm ERR! 
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/dan/dev/haroopad/haroopad/npm-debug.log
```

The repository `github.com/excellenteasy/grunt-shell.git` does not exist. Even if I try replacing the URL in `package.json` with `github.com/sindresorhus/grunt-shell` I'm then presented with a new error.

```

> cson@1.6.1 preinstall /home/dan/dev/haroopad/haroopad/node_modules/grunt-replace/node_modules/applause/node_modules/cson
> node ./cyclic.js


> ambi@2.2.0 preinstall /home/dan/dev/haroopad/haroopad/node_modules/grunt-replace/node_modules/applause/node_modules/cson/node_modules/ambi
> node ./cyclic.js


> typechecker@2.0.8 preinstall /home/dan/dev/haroopad/haroopad/node_modules/grunt-replace/node_modules/applause/node_modules/cson/node_modules/extract-opts/node_modules/typechecker
> node ./cyclic.js


> typechecker@2.0.8 preinstall /home/dan/dev/haroopad/haroopad/node_modules/grunt-replace/node_modules/applause/node_modules/cson/node_modules/ambi/node_modules/typechecker
> node ./cyclic.js


> js2coffee@0.3.3 preinstall /home/dan/dev/haroopad/haroopad/node_modules/grunt-replace/node_modules/applause/node_modules/cson/node_modules/js2coffee
> node ./cyclic.js

npm WARN deprecated uglify-js2@2.1.11: You can now install this using uglify-js@2.2.0 node_modules/uglify-js
npm WARN deprecated ├── source-map@0.1.8 (amdefine@0.0.4)
npm WARN deprecated └── optimist@0.3.5 (wordwrap@0.0.2)
\
> grunt-lodashbuilder@0.1.7 postinstall /home/dan/dev/haroopad/haroopad/node_modules/grunt-requirejs/node_modules/grunt-lodashbuilder
> node ./bin/post-install.js


module.js:340
    throw err;
          ^
Error: Cannot find module '../node_modules/lodash/vendor/tar/tar.js'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at /home/dan/dev/haroopad/haroopad/node_modules/grunt-requirejs/node_modules/grunt-lodashbuilder/bin/post-install.js:14:13
    at Object.<anonymous> (/home/dan/dev/haroopad/haroopad/node_modules/grunt-requirejs/node_modules/grunt-lodashbuilder/bin/post-install.js:166:2)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
npm ERR! Linux 3.16.3-1-ARCH
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! node v0.10.32
npm ERR! npm  v2.1.2
npm ERR! code ELIFECYCLE

npm ERR! grunt-lodashbuilder@0.1.7 postinstall: `node ./bin/post-install.js`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the grunt-lodashbuilder@0.1.7 postinstall script.
npm ERR! This is most likely a problem with the grunt-lodashbuilder package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./bin/post-install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls grunt-lodashbuilder
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/dan/dev/haroopad/haroopad/npm-debug.log
```

**Comment by jluttine** [comment]
Any news on this? I have the same issue. Or is this project dead?

**Comment by dotancohen** [comment]
Confirmed. The repo is gone and Haroopad cannot be installed without it.

**Comment by alexgalkin** [comment]
I have solved this by installing old version of lodash-builder before running npm install:

`npm install grunt-lodashbuilder@0.1.6 --save-dev`
