### ISSUE TITLE
Haroopad doesnt run in win8.1-x64

### ISSUE THREAD

**Issue by ingedgarmorales** [rhiokim/haroopad#578]
Was working well the first time and now it doesn't start anymore. (Win 8.1 64 bit)

haroopad-v0.13.1-win-x64.msi

**Comment by pierrefevrier** [comment]
Same on Windows 7 64 bits.

**Comment by ingedgarmorales** [comment]
I found that uninstall and reinstall does not help to the program runs,  but when you delete the files in `C:\Users\[your_user]\AppData\Local\Haroopad\Cache` _haroopad_ works fine again.

Could anyone confirm this?
Thanks.

**Comment by ghost** [comment]
Doesn't start on Win 10-x64 either.

Uninstall/Reinstall doesnt help. I tried to delete Haroo's cache, doesn't work too.

I got this error log in AppData\Local\Haroopad.error

| ` Information | Description |
| --- | --- |
| Type | UncaughtException |
| Date | Fri Jul 01 2016 15:03:20 GMT+0200 (Paris, Madrid (heure d’été)) |
| Agent | Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/38.0.2125.104 Safari/537.36 |
| Stack | SyntaxError: Unexpected string |

```
at Object.parse (native)
at file:///C:/Users/antgr/AppData/Local/Temp/nw3664_22822/js/app.js:3:13032
at Array.forEach (native)
at load (file:///C:/Users/antgr/AppData/Local/Temp/nw3664_22822/js/app.js:3:12938)
at file:///C:/Users/antgr/AppData/Local/Temp/nw3664_22822/js/app.js:3:13343
at app (file:///C:/Users/antgr/AppData/Local/Temp/nw3664_22822/js/app.js:3:13411)
at file:///C:/Users/antgr/AppData/Local/Temp/nw3664_22822/index.html:1:176
```

| Information | Description |
| --- | --- |
| Type | Error |
| Date | Fri Jul 01 2016 15:03:20 GMT+0200 (Paris, Madrid (heure d’été)) |
| Agent | Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/38.0.2125.104 Safari/537.36 |
| File | file:///C:/Users/antgr/AppData/Local/Temp/nw3664_22822/index.html |
| Line Number | 50 |
| Message | Uncaught SyntaxError: Unexpected string |

`

**Comment by ingedgarmorales** [comment]
Hello MacGros.

Attempts to remove the files in "temp" directory.

Tell us if that has worked for you?

Greetings.

**Comment by ghost** [comment]
Sadly, Nope

| ` Information | Description |
| --- | --- |
| Type | UncaughtException |
| Date | Fri Jul 01 2016 18:03:11 GMT+0200 (Paris, Madrid (heure d’été)) |
| Agent | Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/38.0.2125.104 Safari/537.36 |
| Stack | SyntaxError: Unexpected string |

```
at Object.parse (native)
at file:///C:/Users/antgr/AppData/Local/Temp/nw1096_14452/js/app.js:3:13032
at Array.forEach (native)
at load (file:///C:/Users/antgr/AppData/Local/Temp/nw1096_14452/js/app.js:3:12938)
at file:///C:/Users/antgr/AppData/Local/Temp/nw1096_14452/js/app.js:3:13343
at app (file:///C:/Users/antgr/AppData/Local/Temp/nw1096_14452/js/app.js:3:13411)
at file:///C:/Users/antgr/AppData/Local/Temp/nw1096_14452/index.html:1:176
```

| Information | Description |
| --- | --- |
| Type | Error |
| Date | Fri Jul 01 2016 18:03:11 GMT+0200 (Paris, Madrid (heure d’été)) |
| Agent | Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/38.0.2125.104 Safari/537.36 |
| File | file:///C:/Users/antgr/AppData/Local/Temp/nw1096_14452/index.html |
| Line Number | 50 |
| Message | Uncaught SyntaxError: Unexpected string |

`
